// <auto-generated />
using System;
using EFCodeFirstInvoice.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCodeFirstInvoice.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("invoice.Models.Customer", b =>
                {
                    b.Property<int>("ID_KHACHHANG")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DIA_CHI_KHACH_HANG")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TEN_KHACH_HANG")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID_KHACHHANG");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("invoice.Models.Invoice", b =>
                {
                    b.Property<int>("ID_HOADON")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_KHACHHANG");

                    b.Property<DateTime>("NGAYBAN");

                    b.HasKey("ID_HOADON");

                    b.HasIndex("ID_KHACHHANG");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("invoice.Models.Invoice_detail", b =>
                {
                    b.Property<int>("ID_CTHD")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_HOADON");

                    b.Property<int>("ID_SP");

                    b.Property<int>("SOLUONG");

                    b.Property<double>("THANHTIEN");

                    b.HasKey("ID_CTHD");

                    b.HasIndex("ID_HOADON");

                    b.HasIndex("ID_SP");

                    b.ToTable("Invoice_details");
                });

            modelBuilder.Entity("invoice.Models.Product", b =>
                {
                    b.Property<int>("ID_SP")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GIA");

                    b.Property<string>("MOTA_SP")
                        .IsRequired();

                    b.Property<int>("SOLUONG");

                    b.HasKey("ID_SP");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("invoice.Models.Invoice", b =>
                {
                    b.HasOne("invoice.Models.Customer", "Customers")
                        .WithMany()
                        .HasForeignKey("ID_KHACHHANG")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("invoice.Models.Invoice_detail", b =>
                {
                    b.HasOne("invoice.Models.Invoice", "Invoices")
                        .WithMany()
                        .HasForeignKey("ID_HOADON")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("invoice.Models.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ID_SP")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
